# ===== PostgreSQL Configuration =====
spring.datasource.url=jdbc:postgresql://dpg-d75f2jma2pns738shae0-a.singapore-postgres.render.com:5432/portfolio_2ap2
spring.datasource.username=portfolio_user
spring.datasource.password=UPY6pl8hDWGytBdFQ3APIOZEx7xOJk2Z
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Server =====
server.port=8080