# ===== PostgreSQL Configuration =====
spring.datasource.url=jdbc:postgresql://dpg-d75f2jma2pns738shae0-a:5432/portfolio_2ap2
spring.datasource.username=portfolio_user
spring.datasource.password=UPY6pl8hDWgytBdFQ3APIOZEx7x0Jk2Z
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Server =====
server.port=8080

# ===== Logging =====
logging.level.com.shopeasy=DEBUG